print('Enter the name of dog 1:')
dog_name1 = input()
print('Enter the name of dog 2:')
dog_name2 = input()
print('Enter the name of dog 3:')
dog_name3 = input()
print('Enter the name of dog 4:')
dog_name4 = input()
print('Enter the name of dog 5:')
dog_name5 = input()
print('Enter the name of dog 6:')
dog_name6 = input()

print('The dog names are:')
print(dog_name1 + ' ' + dog_name2 + ' ' + dog_name3 +
      ' ' + dog_name4 + ' ' + dog_name5 + ' ' + dog_name6)
